# Generated by Django 5.0.6 on 2024-05-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_author_birth_date_alter_author_death_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(default='unknown Publisher', max_length=300),
        ),
    ]
